// src/vue/Person/Person.vue
<template>
<tbody>
	<tr class="persons-list__row" v-for="(person, index) of persons" :key="index">
		<td class="persons-list__cell">{{person.id}}</td>
		<td class="persons-list__cell">{{person.name}} {{person.lastName}}</td>
		<td class="persons-list__cell">{{eventName}}</td>
        <td class="persons-list__cell"><button type="button" class="persons-list__delete-btn" @click="() => {deletePerson(eventId, person.id)}">X</button></td>
	</tr>
</tbody>

</template>

<script>


export default {
	data() {
		return {
		}
	},
	methods:{
		deletePerson(eventId, personId) {
			this.$emit('delete-person', eventId, personId)
		}
	},
	props: {
		persons: {
			type: Array,
			required: true
		},
		eventName: {
			type: String,
			required: true
		},
		eventId: {
			type: Number,
		}
    },
}
</script>

<style scoped>
</style>

// src/react/Person/Person.js
import React from 'react';

function Person ({ person, personID, handleDeleteUser, handleEditUser }) {

    return (
        <tr className="persons-list__row">
            <td className="persons-list__cell">{personID}</td>
            <td className="persons-list__cell">{person.lastName}</td>
            <td className="persons-list__cell">{person.name}</td>
            <td className="persons-list__cell">{person.secondName}</td>
            <td className="persons-list__cell"><button onClick={ () => { handleEditUser(person) }}>Edit</button></td>
            <td className="persons-list__cell"><button className="persons-list__delete-btn" onClick={ () => {handleDeleteUser(personID)} }>Х</button></td>
        </tr>
    )
}

export default Person;
